#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"
DOTFILES_ROOT=$(pwd -P)

source $DOTFILES_ROOT/helper.sh

# find the installers and run them iteratively
find . -name install.sh | sort | while read installer ; do sh -c "${installer}" ; done
